# Generated by Django 4.1 on 2022-11-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
