# Generated by Django 4.1 on 2022-11-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furnitureapp', '0002_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='fur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
    ]
